before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/mtdb
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm_6
      - windows_amd64
      - darwin_arm64
    ldflags:
      - -s -w
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
