version: "3.6"

services:
 postgres:
  image: postgres:17.5
  restart: always
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "postgres:/var/lib/postgresql/data"

 integration-test:
  image: golang:1.24.3
  depends_on:
   - postgres
  volumes:
   - "go_dir:/go"
   - "go_cache:/.cache"
   - ".:/data"
  environment:
   - PGUSER=postgres
   - PGPASSWORD=enter
   - PGHOST=postgres
   - PGPORT=5432
   - PGDATABASE=postgres
   - LOGLEVEL=debug
   - GO_FLAGS=-count=1
  working_dir: /data
  command: ["go", "test", "./...", "-cover"]

volumes:
  postgres: {}
  go_cache: {}
  go_dir: {}