version: "3.6"

services:
 postgres:
  image: postgres:14.4
  restart: always
  ports:
   - "5432:5432"
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "postgres:/var/lib/postgresql/data"

 integration-test:
  image: golang:1.19.1
  depends_on:
   - postgres
  volumes:
   - ".:/data"
  environment:
   - PGUSER=postgres
   - PGPASSWORD=enter
   - PGHOST=postgres
   - PGDATABASE=postgres
   - PGPORT=5432
   - LOGLEVEL=debug
  working_dir: /data
  command: ["go", "test", "./...", "-cover"]

volumes:
  postgres: {}
