version: "3.6"

services:
 postgres:
  image: postgres:16.1
  restart: always
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "postgres:/var/lib/postgresql/data"
  command: -c port=9432

 integration-test:
  image: golang:1.21.4
  depends_on:
   - postgres
  volumes:
   - ".:/data"
  environment:
   - PGUSER=postgres
   - PGPASSWORD=enter
   - PGHOST=postgres
   - PGDATABASE=postgres
   - PGPORT=9432
   - LOGLEVEL=debug
   - CGO_ENABLED=0
   - GO_FLAGS=-count=1
  working_dir: /data
  command: ["go", "test", "./...", "-v", "-cover"]

volumes:
  postgres: {}
