name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: enter
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGUSER: postgres
      PGPASSWORD: enter
      PGHOST: localhost
      PGDATABASE: postgres
      PGPORT: 5432
      LOGLEVEL: debug

    steps:
    - name: Install Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: 1.19

    - name: Checkout code
      uses: actions/checkout@v3.5.3

    - name: Test
      run: |
        go test -p 1 ./... -coverprofile=profile.cov

    - uses: shogo82148/actions-goveralls@v1.9.0
      with:
        path-to-profile: profile.cov